server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: provider-service
        uri: lb://provider-service
        predicates:
        - Path=/provider/**
        filters:
        - RewritePath=/provider/(?<path>.*), /$\{path}
      - id: consumer-service
        uri: lb://consumer-service
        predicates:
        - Path=/consumer/**
        filters:
        - RewritePath=/consumer/(?<path>.*), /$\{path}
